version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
    commands:
      - echo Using AWS-managed .NET 6.0 environment...

  pre_build:
    commands:
      - echo "Restore started on $(date)"
      - cd aspnetcore/tutorials/first-mvc-app/start
      - ls -R
      - dotnet restore

  build:
    commands:
      - echo "Build started on $(date)"
      - cd aspnetcore/tutorials/first-mvc-app/start
      - dotnet build --configuration Release

  post_build:
    commands:
      - echo "Publish started on $(date)"
      - cd aspnetcore/tutorials/first-mvc-app/start
      - dotnet publish -c Release -o ./publish

artifacts:
  files:
    - '**/*'
  base-directory: aspnetcore/tutorials/first-mvc-app/start/publish
